import {createStoreScene} from './scene.mjs';
import {createPanorama,SCENES} from './panorama.mjs';
import {createLifeRenderer} from '../../admira-xp/scripts/life-renderer.mjs';
import {createImportedBridge} from '../../admira-xp/scripts/imported-space.mjs';
import {mountDistribuit} from '../../admira-xp/scripts/distribuit-ui.mjs';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),en=params.get('lang')==='en',t=(es,english)=>en?english:es;
if(params.get('embed')==='1')document.documentElement.classList.add('embed');
document.documentElement.lang=en?'en':'es';
$('model-canvas').setAttribute('aria-label',t('Sneakers Store 3D · arrastra para girar y rueda para ampliar','Sneakers Store 3D · drag to orbit and scroll to zoom'));$('inventory-edit').textContent=t('Distribuir','Distribute');$('manage-playlist').textContent=t('Gestionar en admira.biz ↗','Manage in admira.biz ↗');$('manage-playlist').href='https://www.admira.biz/demo/?lang='+(en?'en':'es');
$('scene-kind').textContent=t('Tienda real · recorrido 360','Real store · 360 tour');$('show-playlist').textContent=t('Ver pantalla','View screen');$('close-playlist').setAttribute('aria-label',t('Cerrar','Close'));$('close-inventory').setAttribute('aria-label',t('Cerrar inventario','Close inventory'));$('inventory-title').textContent=t('Inventario','Inventory');$('inventory-note').textContent=t('Planta 3D adaptada a Entrada, Centro y Fondo de IEU. Distribución editable guardada en este navegador; proporciones aproximadas, pendientes de medición.','3D floor plan adapted to IEU Entrance, Centre and Rear. Editable layout saved in this browser; approximate proportions awaiting measurement.');
const video=$('store-video');
const {root,actors,scene,resources,objects,layout,hemisphere,sun,cols,rows,disposeMedia}=createStoreScene({t,video});
let viewMode='photo',panorama;
let viewer,bridge,editor,playlist,index=0,raf=0,disposed=false,mediaTimer;
function apply(next){for(const data of next.layout){const g=objects.get(data.id);if(!g)continue;g.userData.item=data;g.visible=!data.hidden;g.position.set(data.col,g.userData.baseY,data.row);g.rotation.y=-data.rot*Math.PI/2;g.scale.set(data.sx,data.sy,data.sx);}for(const [id,g]of objects)if(!next.layout.some(i=>i.id===id))g.visible=false;}
// A new layout revision leaves the previous demo layout and its edits intact.
const storage={getItem:key=>localStorage.getItem(key+':real-store-v2'),setItem:(key,value)=>localStorage.setItem(key+':real-store-v2',value)};
bridge=createImportedBridge({roomId:'sneakers-store-santa-rosa-19',cols,rows,storage,layout,onSave:next=>{apply(next);viewer?.update({...next,wallHeight:3.2,actors:[]});renderInventory();}});apply(bridge.read());
function status(text){$('store-status').textContent=text;}
try{viewer=createLifeRenderer({canvas:$('model-canvas'),snapshot:{...bridge.read(),wallHeight:3.2,actors:[]},stockCamera:true,sceneFactory:snapshot=>{let state=snapshot;return {scene,world:root,actors,get snapshot(){return state;},update:next=>{state=next;apply(next);},animate:()=>{const angle=viewer?.cameraState.angle??-Math.PI/4;for(const [id,facing] of [['side-wall',Math.cos(angle)>0],['right-wall',Math.cos(angle)<0],['back-wall',Math.sin(angle)<0],['entrance-door',Math.sin(angle)>0]]){const g=objects.get(id);g.visible=facing&&!g.userData.item.hidden;}},refreshMedia:()=>{},screenPreviewIds:[],setLighting:mode=>{hemisphere.intensity=mode==='night'?.8:2.7;sun.intensity=mode==='night'?1.2:4;},dispose:()=>{disposeMedia();resources.forEach(r=>r.dispose());}};},onSelect:data=>{if(editor){editor.select(data);return;}if(data?.item?.id==='screen')openPlaylist();else if(data?.item){status(data.item.label+' · '+t('/distribuir para editar','/distribuir to edit'));}}});viewer.preset('home');viewer.rotate(-Math.PI/(2*.18));const resize=new ResizeObserver(()=>{const r=$('store-stage').getBoundingClientRect();viewer.resize(r.width,r.height);});resize.observe($('store-stage'));const draw=now=>{if(disposed)return;if(viewMode==='model')viewer.render(now);raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);clearInterval(mediaTimer);resize.disconnect();editor?.dispose();bridge.dispose?.();video.pause();video.removeAttribute('src');video.load();panorama?.dispose();viewer.dispose();},{once:true});}catch(e){status(t('No se pudo abrir la escena: ','Could not open the scene: ')+e.message);}
function modeControls(mode){
  $('store-stage').dataset.view=mode;
  $('model-toggle').setAttribute('aria-pressed',String(mode==='model'));
  for(const button of $('tour-controls').querySelectorAll('[data-scene]'))button.setAttribute('aria-pressed',String(mode==='photo'&&button.dataset.scene===panorama?.current));
}
function showModel(){viewMode='model';panorama?.hide();$('model-canvas').hidden=false;$('scene-kind').textContent=t('Planta 3D editable · referencia IEU','Editable 3D floor plan · IEU reference');$('tour-hint').textContent=t('Arrastra para girar · rueda para ampliar','Drag to orbit · scroll to zoom');modeControls('model');const r=$('store-stage').getBoundingClientRect();viewer?.resize(r.width,r.height);}
function showPhoto(id='entrada'){
  if(editor){editor.dispose();editor=null;viewer?.setEditor(null);}
  viewMode='photo';$('model-canvas').hidden=true;
  try{
    panorama??=createPanorama({canvas:$('photo-canvas'),onState:({id,loading})=>{
      $('scene-kind').textContent=(loading?t('Cargando · ','Loading · '):t('Tienda real 360 · ','Real store 360 · '))+SCENES[id][en?'en':'es'];
      if(!loading){$('photo-canvas').dataset.scene=id;modeControls('photo');}
    },onError:()=>{showModel();$('tour-hint').textContent=t('Fotografía no disponible · planta 3D abierta','Photograph unavailable · 3D floor plan opened');}});
    $('tour-hint').textContent=t('Fotografía 360 · arrastra o usa las flechas para mirar alrededor','360 photograph · drag or use arrow keys to look around');modeControls('photo');panorama.show(id);
  }catch{showModel();}
}
$('model-toggle').textContent=t('Planta 3D','3D floor plan');$('model-toggle').onclick=showModel;
$('photo-canvas').setAttribute('aria-label',t('Tienda real en 360 · arrastra o usa las flechas','Real store in 360 · drag or use arrow keys'));
for(const button of $('tour-controls').querySelectorAll('[data-scene]')){button.textContent=SCENES[button.dataset.scene][en?'en':'es'];button.onclick=()=>showPhoto(button.dataset.scene);}
$('camera-link').textContent=t('Puerta Cam ↗','Puerta Cam ↗');$('analytics-link').textContent=t('Segmentación en directo ↗','Live segmentation ↗');
function openPlaylist(){if(!$('playlist-dialog').open)$('playlist-dialog').showModal();video.play().catch(()=>{});}
function edit(){if(!viewer)return;showModel();if(editor){editor.dispose();editor=null;viewer.setEditor(null);return;}editor=mountDistribuit({dialog:$('store-stage'),viewer,bridge,lang:en?'en':'es',onClose:()=>{editor?.dispose();editor=null;viewer.setEditor(null);}});viewer.setEditor(editor);$('store-stage').querySelector('[data-action="catalog"]').hidden=true;}
function renderInventory(){$('inventory-list').replaceChildren(...bridge.read().layout.filter(i=>!i.hidden).map(i=>{const li=document.createElement('li');li.textContent=i.label+' · '+i.id;return li;}));}
function tracks(){const list=$('tracks');list.replaceChildren();playlist.tracks.forEach((track,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.textContent=track.title;b.setAttribute('aria-current',String(i===index));b.onclick=()=>play(i);li.append(b);list.append(li);});$('playlist-title').textContent=playlist.title;$('playlist-status').textContent=playlist.id+' · '+t('revisión ','revision ')+playlist.revision;}
function play(i){if(!playlist?.tracks.length)return;index=i;video.src=playlist.tracks[i].url;video.play().then(()=>status(t('Pantalla conectada · ','Screen connected · ')+playlist.tracks[i].title)).catch(()=>status(t('Playlist conectada · pulsa Ver pantalla para reproducir','Playlist connected · click View screen to play')));tracks();}
video.addEventListener('ended',()=>{if(index+1<playlist.tracks.length)play(index+1);else if(playlist.loop)play(0);});video.addEventListener('error',()=>{const message=t('Error de vídeo · abre la playlist para reintentar.','Video error · open the playlist to retry.');status(message);$('playlist-status').textContent=message;});
async function loadPlaylist(){try{const r=await fetch('https://www.admira.biz/api/demo-global?project=sneakers-store',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!data.playlist){status(t('Escena lista · playlist pendiente en admira.biz/demo/','Scene ready · playlist pending at admira.biz/demo/'));return;}const changed=playlist?.revision!==data.playlist.revision;playlist=data.playlist;if(changed)play(0);}catch(e){status(t('Escena lista · conexión de playlist pendiente: ','Scene ready · playlist connection pending: ')+e.message);}}
$('show-playlist').onclick=openPlaylist;$('close-playlist').onclick=()=>$('playlist-dialog').close();$('close-inventory').onclick=()=>$('inventory-dialog').close();$('inventory-edit').onclick=()=>{$('inventory-dialog').close();edit();};
const actions={'sneakers-entrada':()=>showPhoto('entrada'),'sneakers-centro':()=>showPhoto('centro'),'sneakers-fondo':()=>showPhoto('fondo'),'sneakers-model':showModel,'sneakers-playlist':openPlaylist,'sneakers-edit':edit,'sneakers-home':()=>{showModel();viewer?.preset('home');viewer?.rotate(-Math.PI/(2*.18));},'sneakers-front':()=>{showModel();viewer?.preset('front');viewer?.rotate(-Math.PI/.18);},'sneakers-floor':()=>{showModel();viewer?.preset('floor');},'sneakers-plus':()=>viewMode==='photo'?panorama?.zoom(1.15):viewer?.zoomBy(1.15),'sneakers-minus':()=>viewMode==='photo'?panorama?.zoom(1/1.15):viewer?.zoomBy(1/1.15),'sneakers-day':()=>{showModel();viewer?.setLighting('day');},'sneakers-night':()=>{showModel();viewer?.setLighting('night');},'sneakers-inventory':()=>{renderInventory();$('inventory-dialog').showModal();}};
document.addEventListener('click',e=>{const a=e.target.closest('[id]');actions[a?.id]?.();});
function register(){if(!window.XpaceShell?.registerVerb){setTimeout(register,100);return;}window.XpaceShell.registerVerb({id:'distribuir',es:'Editar mobiliario de Sneakers Store',en:'Edit Sneakers Store furniture',run:()=>{edit();return t('Editor de Sneakers Store','Sneakers Store editor');}});window.XpaceShell.registerVerb({id:'inventario',es:'Inventario de Sneakers Store',en:'Sneakers Store inventory',run:()=>{actions['sneakers-inventory']();return 'SneakerStore';}});}
window.addEventListener('admira:languagechange',e=>{const next=e.detail?.lang;if(['es','en'].includes(next)&&next!==(en?'en':'es')){const u=new URL(location.href);u.searchParams.set('lang',next);location.assign(u.href);}});
register();showPhoto(params.get('scene') in SCENES?params.get('scene'):'entrada');if(params.get('view')==='model')showModel();status(t('Escena lista · conectando playlist…','Scene ready · connecting playlist…'));loadPlaylist();mediaTimer=setInterval(loadPlaylist,15000);
