import {createCreatorCampaign} from './next-step/creator-core.mjs?v=creator-full-1';
import {mountNextStep} from './next-step/twin.mjs?v=creator-full-1';
import {compatibleTrack,measuredFormat} from './screen-format.mjs';
import * as T from '../../admira-xp/scripts/premium-three.mjs';
import {referenceStorage} from './layout-reference.mjs?v=rear-8';
import {createStoreScene} from './scene.mjs?v=next-step-1';
import {createPanorama,SCENES} from './panorama.mjs?v=creator-full-1';
import {createLifeRenderer} from '../../admira-xp/scripts/life-renderer.mjs';
import {createImportedBridge} from '../../admira-xp/scripts/imported-space.mjs';
import {mountDistribuit} from '../../admira-xp/scripts/distribuit-ui.mjs';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),en=params.get('lang')==='en',t=(es,english)=>en?english:es;
let creatorCampaign=null;try{if(params.has('creator'))creatorCampaign=createCreatorCampaign(params.get('creator'),en);}catch{params.delete('creator');}
let fullInvalid=false;if(params.get('mode')==='full'){const image=params.get('image'),video=params.get('video');if(creatorCampaign&&/^[a-zA-Z0-9_-]{6,100}$/.test(image||'')&&/^[a-zA-Z0-9_-]{6,100}$/.test(video||'')){creatorCampaign={...creatorCampaign,mode:'full',image:{id:image,url:'https://api.admira.store/stock/asset/'+image},video:{id:video,url:'https://api.admira.store/stock/asset/'+video},generatedBy:'Imagen 4 + Grok Imagine Video'};}else{fullInvalid=true;creatorCampaign=null;}}
const campaignName=creatorCampaign?.name||'NEXT STEP';
if(params.get('embed')==='1')document.documentElement.classList.add('embed');
document.documentElement.lang=en?'en':'es';
$('global-demo-link').href='https://www.admira.biz/demo/?lang='+(en?'en':'es');
$('model-canvas').setAttribute('aria-label',t('Sneakers Store 3D · arrastra para girar y rueda para ampliar','Sneakers Store 3D · drag to orbit and scroll to zoom'));$('inventory-edit').textContent=t('Distribuir','Distribute');$('manage-playlist').textContent=t('Gestionar en admira.biz ↗','Manage in admira.biz ↗');$('manage-playlist').href='https://www.admira.biz/demo/?lang='+(en?'en':'es');
$('scene-kind').textContent=t('Tienda real · recorrido 360','Real store · 360 tour');$('show-playlist').textContent=t('Ver pantalla','View screen');$('close-playlist').setAttribute('aria-label',t('Cerrar','Close'));$('close-inventory').setAttribute('aria-label',t('Cerrar inventario','Close inventory'));$('inventory-title').textContent=t('Inventario','Inventory');$('inventory-note').textContent=t('Planta 3D adaptada a Entrada, Centro y Fondo de IEU. Distribución editable guardada en este navegador; proporciones aproximadas, pendientes de medición.','3D floor plan adapted to IEU Entrance, Centre and Rear. Editable layout saved in this browser; approximate proportions awaiting measurement.');
const video=$('store-video'),portraitVideo=$('portrait-video');
const channels={horizontal:{video,playlist:null,index:0,rejected:new Set()},vertical:{video:portraitVideo,playlist:null,index:0,rejected:new Set()}};let selectedChannel='horizontal';
$('playlist-channel').setAttribute('aria-label',t('Formato de pantalla','Screen format'));$('playlist-channel').options[0].text=t('LCD + LED · horizontal','LCD + LED · landscape');$('playlist-channel').options[1].text=t('Entrada · vertical','Entrance · portrait');
const {root,actors,scene,resources,objects,layout,hemisphere,sun,cols,rows,disposeMedia,setCampaignMode}=createStoreScene({t,video,portraitVideo});
let viewMode='photo',modelView='overview',panorama,campaignDemo=null,campaignStarting=null;
let viewer,bridge,editor,raf=0,disposed=false,mediaTimer;
function apply(next){for(const data of next.layout){const g=objects.get(data.id);if(!g)continue;g.userData.item=data;g.visible=!data.hidden;g.position.set(data.col,g.userData.baseY,data.row);g.rotation.y=-data.rot*Math.PI/2;g.scale.set(data.sx,data.sy,data.sx);}for(const [id,g]of objects)if(!next.layout.some(i=>i.id===id))g.visible=false;}
// Back up v2 once, correct untouched default poses and retain deliberate edits.
const storage=referenceStorage(localStorage,layout);
bridge=createImportedBridge({roomId:'sneakers-store-santa-rosa-19',cols,rows,storage,layout,onSave:next=>{apply(next);viewer?.update({...next,wallHeight:3.2,actors:[]});renderInventory();}});apply(bridge.read());
function status(text){$('store-status').textContent=text;}
try{viewer=createLifeRenderer({canvas:$('model-canvas'),snapshot:{...bridge.read(),wallHeight:3.2,actors:[]},stockCamera:true,sceneFactory:snapshot=>{let state=snapshot;return {scene,world:root,actors,get snapshot(){return state;},update:next=>{state=next;apply(next);},animate:()=>{const angle=viewer?.cameraState.angle??-Math.PI/4;for(const [id,facing] of [['side-wall',Math.cos(angle)>0],['right-wall',Math.cos(angle)<0],['back-wall',Math.sin(angle)<0],['rear-door',Math.sin(angle)<0],['entrance-door',Math.sin(angle)>0]]){const g=objects.get(id);g.visible=facing&&!g.userData.item.hidden;}},refreshMedia:()=>{},screenPreviewIds:[],setLighting:mode=>{hemisphere.intensity=mode==='night'?.8:2.7;sun.intensity=mode==='night'?1.2:4;},dispose:()=>{disposeMedia();resources.forEach(r=>r.dispose());}};},onSelect:data=>{if(editor){editor.select(data);return;}if(['screen','back-wall'].includes(data?.item?.id))openPlaylist('horizontal');else if(data?.item?.id==='entry-display')openPlaylist('vertical');else if(data?.item){status(data.item.label+' · '+t('/distribuir para editar','/distribuir to edit'));}}});viewer.preset('home');viewer.rotate(-Math.PI/.18);const resize=new ResizeObserver(()=>{const r=$('store-stage').getBoundingClientRect();viewer.resize(r.width,r.height);});resize.observe($('store-stage'));const draw=now=>{if(disposed)return;const changed=campaignDemo?.update(now);if(viewMode==='model')viewer.render(now);else if(changed)panorama?.render();raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);clearInterval(mediaTimer);resize.disconnect();editor?.dispose();campaignDemo?.stop();bridge.dispose?.();for(const {video} of Object.values(channels)){video.pause();video.removeAttribute('src');video.load();}panorama?.dispose();viewer.dispose();},{once:true});}catch(e){status(t('No se pudo abrir la escena: ','Could not open the scene: ')+e.message);}
function modeControls(mode){
  $('store-stage').dataset.view=mode;
  $('model-toggle').setAttribute('aria-pressed',String(mode==='model'&&modelView==='overview'));
  $('rear-toggle').setAttribute('aria-pressed',String(mode==='model'&&modelView==='rear'));
  $('jordan-toggle').setAttribute('aria-pressed',String(mode==='model'&&modelView==='wall'));
  for(const button of $('tour-controls').querySelectorAll('[data-scene]'))button.setAttribute('aria-pressed',String(mode==='photo'&&button.dataset.scene===panorama?.current));
}
function showModel(){if(modelView!=='overview'){viewer?.preset('home');viewer?.rotate(-Math.PI/.18);}modelView='overview';viewMode='model';panorama?.hide();$('model-canvas').hidden=false;$('scene-kind').textContent=t('Planta 3D editable · referencia IEU','Editable 3D floor plan · IEU reference');$('tour-hint').textContent=t('Desde la calle hacia caja: LCD a la izquierda · recreativas a la derecha','Street to checkout: LCD on the left · arcades on the right');modeControls('model');const r=$('store-stage').getBoundingClientRect();viewer?.resize(r.width,r.height);}
function showRear(){showModel();modelView='rear';const frame=new T.Group();for(const id of ['back-wall','rear-door','counter','bench'])frame.add(objects.get(id).clone(true));viewer?.frameObject(frame,{angle:-Math.PI/2,elevation:.08,clip:true,margin:1.45});modeControls('model');$('tour-hint').textContent=campaignDemo?t(campaignName+' · LED con puerta central · composición propia del fondo',campaignName+' · LED with central door · dedicated rear composition'):t('Fondo: pantalla LED · puerta central · mesa pegada a la pared derecha. Vídeo horizontal compartido con la LCD.','Rear: LED screen · central door · table against the right wall. Landscape video shared with the LCD.');}
function showJordan(){showModel();modelView='wall';const frame=new T.Group();for(const id of ['entry-display','left-video-bank','screen'])frame.add(objects.get(id).clone(true));viewer?.frameObject(frame,{angle:Math.PI,elevation:.02,clip:true,margin:1.25});modeControls('model');$('tour-hint').textContent=campaignDemo?t(campaignName+' · Jordan a la izquierda, LCD a su derecha · reloj compartido',campaignName+' · Jordan on the left, LCD to its right · shared clock'):t('Pared de frente: Jordan a la izquierda · LCD a su derecha. Jordan: captura IEU; LCD: playlist.','Facing the wall: Jordan on the left · LCD to its right. Jordan: IEU still; LCD: playlist.');}
function showPhoto(id='entrada'){
  if(editor){editor.dispose();editor=null;viewer?.setEditor(null);}
  viewMode='photo';$('model-canvas').hidden=true;
  try{
    panorama??=createPanorama({canvas:$('photo-canvas'),onState:({id,loading})=>{
      $('scene-kind').textContent=(loading?t('Cargando · ','Loading · '):t('Tienda real 360 · ','Real store 360 · '))+SCENES[id][en?'en':'es'];
      if(!loading){$('photo-canvas').dataset.scene=id;modeControls('photo');}
    },onError:()=>{showModel();$('tour-hint').textContent=t('Fotografía no disponible · planta 3D abierta','Photograph unavailable · 3D floor plan opened');}});
    $('tour-hint').textContent=t('Fotografía 360 · arrastra o usa las flechas para mirar alrededor','360 photograph · drag or use arrow keys to look around');modeControls('photo');panorama.setCampaign(campaignDemo);panorama.show(id);
  }catch{showModel();}
}
$('rear-toggle').textContent=t('Fondo LED','Rear LED');$('rear-toggle').onclick=showRear;
$('jordan-toggle').textContent=t('Jordan + LCD','Jordan + LCD');$('jordan-toggle').onclick=showJordan;
$('model-toggle').textContent=t('Planta 3D','3D floor plan');$('model-toggle').onclick=showModel;
$('photo-canvas').setAttribute('aria-label',t('Tienda real en 360 · arrastra o usa las flechas','Real store in 360 · drag or use arrow keys'));
for(const button of $('tour-controls').querySelectorAll('[data-scene]')){button.textContent=SCENES[button.dataset.scene][en?'en':'es'];button.onclick=()=>showPhoto(button.dataset.scene);}
$('camera-link').textContent=t('Puerta Cam ↗','Puerta Cam ↗');$('analytics-link').textContent=t('Segmentación en directo ↗','Live segmentation ↗');
function openPlaylist(channel=selectedChannel){if(campaignDemo){location.assign(creatorCampaign?'https://admira.studio/creador/?demo=creador&seed='+creatorCampaign.seed+'&lang='+(en?'en':'es')+(creatorCampaign.mode==='full'?'&mode=full':''):'https://admira.studio/campanas/next-step/?lang='+(en?'en':'es'));return;}if(typeof channel==='string')selectedChannel=channel;$('playlist-channel').value=selectedChannel;tracks();if(!$('playlist-dialog').open)$('playlist-dialog').showModal();const c=channels[selectedChannel];if(c.valid)c.video.play().catch(()=>{});}
$('playlist-channel').onchange=()=>openPlaylist($('playlist-channel').value);
function edit(){if(!viewer)return;showModel();if(editor){editor.dispose();editor=null;viewer.setEditor(null);return;}editor=mountDistribuit({dialog:$('store-stage'),viewer,bridge,lang:en?'en':'es',onClose:()=>{editor?.dispose();editor=null;viewer.setEditor(null);}});viewer.setEditor(editor);$('store-stage').querySelector('[data-action="catalog"]').hidden=true;}
function renderInventory(){$('inventory-list').replaceChildren(...bridge.read().layout.filter(i=>!i.hidden).map(i=>{const li=document.createElement('li');li.textContent=i.label+' · '+i.id;return li;}));}
function tracks(){const c=channels[selectedChannel],p=c.playlist;const list=$('tracks');list.replaceChildren();for(const [format,state] of Object.entries(channels))state.video.hidden=format!==selectedChannel;
 $('playlist-title').textContent=p?.title||t('Playlist pendiente','Playlist pending');$('playlist-status').textContent=p?p.id+' · '+selectedChannel+' · '+t('revisión ','revision ')+p.revision:t('Sin contenidos compatibles','No compatible content');
 p?.tracks.forEach((track,i)=>{const li=document.createElement('li'),b=document.createElement('button');const compatible=compatibleTrack(track,selectedChannel)&&!c.rejected.has(track.id);b.textContent=track.title+(compatible?'':' · '+t('formato incompatible','incompatible format'));b.disabled=!compatible;b.setAttribute('aria-current',String(i===c.index));b.onclick=()=>play(selectedChannel,i);li.append(b);list.append(li);});}
function play(format,i){const c=channels[format],p=c.playlist;c.valid=false;c.video.pause();if(!p?.tracks.length)return;
 const next=p.tracks.findIndex((track,j)=>j>=i&&compatibleTrack(track,format)&&!c.rejected.has(track.id));
 if(next<0){c.video.removeAttribute('src');c.video.load();status(t('Sin contenidos compatibles · ','No compatible content · ')+format);tracks();return;}
 c.index=next;c.video.src=p.tracks[next].url;c.video.load();tracks();}
for(const [format,c] of Object.entries(channels)){
 c.video.addEventListener('loadedmetadata',()=>{if(campaignDemo||campaignStarting)return;const actual=measuredFormat(c.video.videoWidth,c.video.videoHeight),track=c.playlist?.tracks[c.index];
  if(actual!==format){if(track)c.rejected.add(track.id);status(t('Bloqueado: dimensiones incompatibles · ','Blocked: incompatible dimensions · ')+format);play(format,c.index+1);return;}
  c.valid=true;c.video.play().then(()=>{if(format==='horizontal'&&!campaignDemo&&!campaignStarting)status(t('LCD horizontal conectada · ','Landscape LCD connected · ')+track.title);}).catch(()=>{if(!campaignDemo&&!campaignStarting)status(t('Pulsa Ver pantalla para reproducir','Click View screen to play'));});
 });
 c.video.addEventListener('ended',()=>{const next=c.index+1;if(next<c.playlist.tracks.length)play(format,next);else if(c.playlist.loop)play(format,0);});
 c.video.addEventListener('error',()=>{if(c.video.getAttribute('src'))status(t('Error de vídeo · ','Video error · ')+format);});
}
async function loadPlaylist(){if(campaignDemo||campaignStarting)return;await Promise.all(Object.entries(channels).map(async([format,c])=>{try{const r=await fetch('https://www.admira.biz/api/demo-global?project=sneakers-store&channel='+format,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(campaignDemo||campaignStarting||!data.playlist)return;
 const signature=JSON.stringify([data.playlist.revision,data.playlist.tracks.map(t=>[t.id,t.url,t.tags])]);const changed=c.signature!==signature;c.playlist=data.playlist;c.signature=signature;if(changed){c.rejected.clear();play(format,0);}
 }catch(e){status(t('Conexión de playlist pendiente: ','Playlist connection pending: ')+format+' · '+e.message);}}));}
$('show-playlist').onclick=openPlaylist;$('close-playlist').onclick=()=>$('playlist-dialog').close();$('close-inventory').onclick=()=>$('inventory-dialog').close();$('inventory-edit').onclick=()=>{$('inventory-dialog').close();edit();};
const actions={'sneakers-rear':showRear,'sneakers-jordan':showJordan,'sneakers-entrada':()=>showPhoto('entrada'),'sneakers-centro':()=>showPhoto('centro'),'sneakers-fondo':()=>showPhoto('fondo'),'sneakers-model':showModel,'sneakers-playlist':openPlaylist,'sneakers-edit':edit,'sneakers-home':()=>{showModel();viewer?.preset('home');viewer?.rotate(-Math.PI/.18);},'sneakers-front':()=>{showModel();viewer?.preset('front');viewer?.rotate(-Math.PI/.18);},'sneakers-floor':()=>{showModel();viewer?.preset('floor');},'sneakers-plus':()=>viewMode==='photo'?panorama?.zoom(1.15):viewer?.zoomBy(1.15),'sneakers-minus':()=>viewMode==='photo'?panorama?.zoom(1/1.15):viewer?.zoomBy(1/1.15),'sneakers-day':()=>{showModel();viewer?.setLighting('day');},'sneakers-night':()=>{showModel();viewer?.setLighting('night');},'sneakers-inventory':()=>{renderInventory();$('inventory-dialog').showModal();}};
document.addEventListener('click',e=>{const a=e.target.closest('[id]');actions[a?.id]?.();});
async function campaign(command=''){
 if(fullInvalid)throw Error('creator-full-media-missing');const action=String(command).trim().toLowerCase();
 if(campaignStarting){await campaignStarting;}
 if(/^(stop|parar|detener|off)$/.test(action)){panorama?.setCampaign(null);campaignDemo?.stop();campaignDemo=null;setCampaignMode(false);for(const c of Object.values(channels))if(c.valid)c.video.play().catch(()=>{});$('campaign-toggle').textContent='▶ '+campaignName;const message=t('Campaña detenida · playlist anterior recuperada','Campaign stopped · previous playlist restored');$('tour-hint').textContent=message;status(message);void loadPlaylist();return message;}
 if(!campaignDemo){setCampaignMode(true);$('campaign-toggle').disabled=true;campaignStarting=mountNextStep({objects,en,creator:creatorCampaign});try{campaignDemo=await campaignStarting;for(const c of Object.values(channels))c.video.pause();}catch(e){setCampaignMode(false);throw e;}finally{campaignStarting=null;$('campaign-toggle').disabled=false;}panorama?.setCampaign(campaignDemo);if(viewMode==='model'&&modelView==='rear')showRear();else if(viewMode==='model'&&modelView==='wall')showJordan();}
 if(/^(pause|pausa|pausar)$/.test(action))campaignDemo.pause();else if(/^(restart|reiniciar)$/.test(action))campaignDemo.restart();else campaignDemo.play();
 $('campaign-toggle').textContent='■ '+campaignName;$('tour-hint').textContent=campaignName+' · '+t(' pantallas en 360 y 3D · una secuencia compartida','screens in 360 and 3D · one shared sequence');status(campaignName+' · '+(campaignDemo.paused?t('Pausada · demo en el gemelo digital','Paused · digital twin demo'):t('Activa · demo en el gemelo digital','Active · digital twin demo')));return campaignName+' · '+t('7 configuraciones · 13 piezas','7 configurations · 13 pieces');
}
$('campaign-toggle').textContent='▶ '+campaignName;$('campaign-toggle').onclick=()=>void campaign(campaignDemo?'stop':'').catch(e=>status(t('No se pudo abrir NEXT STEP: ','NEXT STEP could not open: ')+e.message));
function register(){if(!window.XpaceShell?.registerVerb){setTimeout(register,100);return;}window.XpaceShell.registerVerb({id:'campana',es:'NEXT STEP: pantallas 360 y 3D; pausa, reiniciar, parar',en:'NEXT STEP: 360 and 3D screens; pause, restart, stop',run:campaign});window.XpaceShell.registerVerb({id:'demo',es:'/demo creador todo: imagen y vídeo IA nuevos hasta 360; /demo sneakers: campaña NEXT STEP; /demo global: proyecto y Xpacio',en:'/demo creator full: new AI image and video into 360; /demo sneakers: NEXT STEP campaign; /demo global: project and venue',run:args=>/^(creador|creator)(?:\s|$)/i.test(args)?(location.assign('https://admira.studio/creador/?demo=creador&lang='+(en?'en':'es')+(/(?:^|\s)(todo|full)$/.test(args)?'&mode=full&intent=full':'')),'Demo Creador'):/^global(?:\s|$)/i.test(args)?(location.assign('https://www.admira.biz/demo/?lang='+(en?'en':'es')),'Demo global'):campaign(args.replace(/^(?:sneakers?|next-step|nextstep)\s*/i,''))});window.XpaceShell.registerVerb({id:'distribuir',es:'Editar mobiliario de Sneakers Store',en:'Edit Sneakers Store furniture',run:()=>{edit();return t('Editor de Sneakers Store','Sneakers Store editor');}});window.XpaceShell.registerVerb({id:'inventario',es:'Inventario de Sneakers Store',en:'Sneakers Store inventory',run:()=>{actions['sneakers-inventory']();return 'SneakerStore';}});}
window.addEventListener('admira:languagechange',e=>{const next=e.detail?.lang;if(['es','en'].includes(next)&&next!==(en?'en':'es')){const u=new URL(location.href);u.searchParams.set('lang',next);location.assign(u.href);}});
register();showPhoto(params.get('scene') in SCENES?params.get('scene'):'entrada');if(params.get('view')==='model')showModel();if(params.get('view')==='jordan')showJordan();if(params.get('view')==='rear')showRear();status(t('Escena lista · conectando playlist…','Scene ready · connecting playlist…'));loadPlaylist();mediaTimer=setInterval(loadPlaylist,15000);

if(fullInvalid)status(t('Medios IA de la campaña ausentes. Abre el contrato o vuelve a Creador.','Campaign AI media missing. Open the contract or return to Creator.'));
if(params.get('campaign')==='next-step'||creatorCampaign)void campaign().then(()=>{if(!creatorCampaign||parent===window)return;let origin;try{origin=new URL(document.referrer).origin;}catch{return;}if(['https://admira.studio','https://www.admira.studio','https://pixeria.com','https://www.pixeria.com'].includes(origin))parent.postMessage({type:'admira:creator-ready',seed:creatorCampaign.seed},origin);}).catch(e=>{status(t('Campaña pendiente: ','Campaign pending: ')+e.message);let origin;try{origin=new URL(document.referrer).origin;}catch{return;}if(creatorCampaign&&['https://admira.studio','https://www.admira.studio','https://pixeria.com','https://www.pixeria.com'].includes(origin))parent.postMessage({type:'admira:creator-error',seed:creatorCampaign.seed,error:e.message},origin);});

window.addEventListener('message',e=>{if(e.source!==parent||!['https://admira.studio','https://www.admira.studio','https://pixeria.com','https://www.pixeria.com'].includes(e.origin)||e.data?.type!=='admira:creator-control'||e.data.seed!==creatorCampaign?.seed||!campaignDemo)return;const action={pause:'pause',resume:'resume',stop:'stop'}[e.data.action];if(action)void campaign(action).catch(()=>{});});
